services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  System25\T3sports\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/Model/*']

  # public, damit das Autowiring beim Hook-Aufruf klappt. Gibt es ein Tag für Hooks?
  System25\T3sports\Hooks\ClearStats:
      public: true
  System25\T3sports\Command\CalculateSeriesCommand:
    tags:
      - name: 'console.command'
        command: 't3sports:stats:calculate-series'
        schedulable: false
        description: calculate a match series in T3sportstats
