name: PHP Checks

on: [push, pull_request]

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.4
            -
              name: "Install composer dependencies"
              run: "composer install --no-interaction --no-progress --no-suggest"
            - run: composer require friendsofphp/php-cs-fixer:3.8.0
            - run: .Build/bin/php-cs-fixer fix --diff --dry-run
